spring.application.name=warranty-mscv

server.port=8004

spring.datasource.url=jdbc:h2:file:./data/warranties
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

# Consola de administración de H2
spring.h2.console.enabled=true

# 🛠 CORRECCIÓN DE SWAGGER (Limpio y compatible con Spring Boot 4 / Springdoc 3)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Cambia la ruta base visual a algo limpio si no quieres usar la ruta por defecto
springdoc.swagger-ui.path=/swagger-ui.html